kind: Service
apiVersion: v1
metadata:
  name: adf-kibana-service
  labels:
    app: adf-kibana
spec:
  type: NodePort
  selector:
    app: adf-kibana
  ports:
    - port: 5600
      targetPort: 5600
      nodePort: 30002