apiVersion: apps/v1
kind: Deployment
metadata:
  name: adf-es7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adf-es7
  template:
    metadata:
      labels:
        app: adf-es7
    spec:
      containers:
        - name: adf-es7
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx2G -Xms2G"
          image: elasticsearch:7.9.3
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          resources:
            limits:
              cpu: 2000m
              memory: 4G
            requests:
              cpu: 1000m
              memory: 2G
      volumes:
        - name: config-volume
          configMap:
            name: adf-es7-config
      initContainers:
        - name: configure-sysctl
          securityContext:
            runAsUser: 0
            privileged: true
          image: "elasticsearch:7.9.3"
          command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
          resources: {}

