apiVersion: apps/v1
kind: Deployment
metadata:
  name: adf-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adf-kibana
  template: 
    metadata:
      labels:
        app: adf-kibana
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: config-volume
          mountPath: /etc/nginx/.htpasswd
          subPath: basic_auth
        - name: config-volume
          mountPath: /html/404.html
          subPath: 404.html
        - name: config-volume
          mountPath: /html/401.html
          subPath: 401.html
        - name: config-volume
          mountPath: /html/50x.html
          subPath: 50x.html
        ports:
        - containerPort: 5600
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 500m
            memory: 256Mi
      - name: kibana
        image: kibana:7.9.3
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
            memory: 2G
          requests:
            cpu: 500m
            memory: 1G
      volumes:
      - name: config-volume
        configMap:
          name: adf-kibana-config

