apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
data:
  # example of a simple property defined using --from-literal
  example.property.1: hello
  example.property.2: world
  # example of a complex property defined using --from-file
  dm.properties: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3