kind: Service
apiVersion: v1
metadata:
  name: preprod-spboot-service
  labels:
    app: spboot-v2
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: spboot-v2
  ports:
    - port: 80
      targetPort: 9080