kind: Service
apiVersion: v1
metadata:
  name: prod-spboot-service
  labels:
    app: spboot-v1
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: spboot-v1
  ports:
    - port: 80
      targetPort: 9080