apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spboot-demo
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: spboot-demo
    spec:
      containers:
      - name: spboot-container
        image: nilaybose/mkubedemo
        ports:
        - containerPort: 9080
