apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spboot-v1
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: spboot-v1
    spec:
      containers:
      - name: spboot-container
        image: nilaybose/mkubedemo
        env:
          - name: DB_USER_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        volumeMounts:
        - name: sblogs
          mountPath: /tmp/sblogs
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 9080
      volumes:
      - name: sblogs
        hostPath: 
         path: /tmp/sblogs
      - name: config-volume
        configMap:
          name: example-config

